AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-movie-recommendation
  Sample SAM Template for serverless-movie-recommendation

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    Runtime: python3.9

Resources:
  MovieRecommendationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  MovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: main.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref MovieRecommendationApi
      Environment:
        Variables:
          MOVIES_TABLE: !Ref MoviesTable
          RATINGS_TABLE: !Ref RatingsTable

  MoviesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: movies-table
      AttributeDefinitions:
        - AttributeName: movie_id
          AttributeType: S
      KeySchema:
        - AttributeName: movie_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  RatingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ratings-table
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: movie_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: movie_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${MovieRecommendationApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
